### PR TITLE
Fix mypy line in test workflow

### PR DESCRIPTION
**Pull request by arturomf94**
## Description

It looks like the `mypy` command is not being found. For example, see [this](https://github.com/OpenMined/SyMPC/pull/15/checks?check_run_id=1568386019) run or [this](https://github.com/OpenMined/SyMPC/runs/1545245419) run.

This PR adds a line to install `mypy` correctly.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by arturomf94** [comment]
@aanurraj unless we want to keep this... In that case maybe let's try to fix that command. It probably just needs installing beforehand... What is `mypy` supposed to do?

**Review by LaRiffle — APPROVED** [review]
Yeah I'd say we can remove it!
@gmuraru is this ok?

**Comment by arturomf94** [comment]
@LaRiffle - we agreed during the meeting today that it might make more sense to install `mypy` correctly. So I'll edit the PR and do that instead.

**Comment by arturomf94** [comment]
It works now! See [this](https://github.com/OpenMined/SyMPC/pull/24/checks?check_run_id=1572346239). Keep in mind we still need to adress the type errors...

**Review by LaRiffle — APPROVED** [review]
Ok this is great!

**Review by gmuraru — APPROVED** [review]

**Pull request merged**
