### PR TITLE
Revert "Solves cancelling previous jobs #102"

### PR DESCRIPTION
**Pull request by gmuraru**
Reverts OpenMined/SyMPC#116

### CODE REVIEW

**Comment by gmuraru** [comment]
It seems like there is an error, if you look [here](https://github.com/OpenMined/SyMPC/runs/2364566932?check_suite_focus=true):
```
{
  eventName: 'pull_request',
  sha: 'b75deaf8cfb33ddc86f5c271c1d84c0ca5157627',
  headSha: 'c48d0ccfca35be233ee55fb3c1faec745a282613',
  branch: 'gm-test',
  owner: 'OpenMined',
  repo: 'SyMPC',
  GITHUB_RUN_ID: '756441954'
}
Found token: yes
Found workflow_id: ["5429972"]
Found 2 runs total.
Found 1 runs to cancel.
Canceling run:  {
  id: 756438378,
  head_sha: '38d46761433fbac575594fdd9628982aafd0c03b',
  status: 'in_progress',
  html_url: 'https://github.com/OpenMined/SyMPC/actions/runs/756438378'
}
Error while canceling workflow_id 5429972: Resource not accessible by integration

Cancel Complete.
```

**Comment by radhikasethi2011** [comment]
I was just wondering. 
Came accross [this](https://stackoverflow.com/questions/63638496/any-idea-why-my-github-app-manages-to-update-the-file-content-using-the-same-ser) 

 The access token generated after the user login will not be able to access the GitHub API. We need a Personal Access Token generated to hit the API and make it work.

**Comment by radhikasethi2011** [comment]
> I was just wondering. 
> Came accross [this](https://stackoverflow.com/questions/63638496/any-idea-why-my-github-app-manages-to-update-the-file-content-using-the-same-ser) 
> 
>  The access token generated after the user login will not be able to access the GitHub API. We need a Personal Access Token generated to hit the API and make it work.
> 

Will this be a good way to approach the problem?

**Comment by gmuraru** [comment]
I was looking into this: https://github.com/potiuk/cancel-workflow-runs#fail-fast-workflow-runs-with-failed-jobs <-- maybe this might work better?

**Comment by radhikasethi2011** [comment]
> I was looking into this: https://github.com/potiuk/cancel-workflow-runs#fail-fast-workflow-runs-with-failed-jobs <-- maybe this might work better?

Okay looking into it! 
(Will be back soon)

**Pull request merged**
