### PR TITLE
Set the session as "globals" in the party

### PR DESCRIPTION
**Pull request by linamnt**
## Description
Closes https://github.com/OpenMined/SyMPC/issues/66.

### General
- [x] Add `session` to globals in deserialize function of https://github.com/OpenMined/PySyft/blob/dev/src/syft/lib/sympc/session_util.py (See https://github.com/OpenMined/PySyft/pull/5515)
- [x] create `get_session()` in utils.py

### parallel_execution functions
- [x] mask_builder
- [x] evaluate
- [x] spdz_mask
- [x] mul_parties
- [x] div_wraps

### Steps for each fn:
- use `get_session` within each function
- remove session from args
- remove passing of session pointers to parallel_execution 

## How has this been tested?
- Ran the tests for PySyft using this code on my environment (Python 3.8.5)
- Not yet passing on sympc tests

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by gmuraru** [comment]
@linamnt  Could you solve the conflict and push again?

**Comment by gmuraru** [comment]
Hello @linamnt. The changes from here are working! (also took the PySyft branch).

I approve your PR and also added @LaRiffle to the reviewers :D -- tomorrow I think we will merge this.

**Review by gmuraru — APPROVED** [review]
LGTM!

**Comment by LaRiffle** [comment]
Looks good to me! But the tests need to be fixed
So this change means that we won't be able to process simultaneously to computations with different session right? Are we OK with this?

**Comment by gmuraru** [comment]
> Looks good to me! But the tests need to be fixed
> So this change means that we won't be able to process simultaneously to computations with different session right? Are we OK with this?

Yep, for the moment it is ok! We can extend this to do
`get_session(UUID_session)` in case we want to train multiple parties

**Comment by gmuraru** [comment]
Closing this as those changes are addressed [here](https://github.com/OpenMined/SyMPC/pull/190)

**Pull request closed without merging**
